"""Markdown archive: export vault.db → archive/YYYY-MM-DD/YYYY-MM-DD.md

Format:
  - One .md per day (in user's local timezone), grouped by chat
  - Each message: timestamp + sender + msg_type + text
  - Attachment reference: file path (relative to vault root)
"""
import datetime
import json
import os
import sqlite3

from . import config


def archive_day(target_date: datetime.date = None, tz_offset_hours: int = 8) -> dict:
    """Export messages from target_date to markdown.

    Args:
        target_date: date to export, default = today (local)
        tz_offset_hours: user's UTC offset for day boundary, default +8 (CST)
    """
    if target_date is None:
        target_date = (datetime.datetime.now(datetime.timezone.utc) +
                       datetime.timedelta(hours=tz_offset_hours)).date()

    init_db_or_open()
    conn = sqlite3.connect(str(config.VAULT_DB))
    cur = conn.cursor()

    # Compute UTC time range for target_date in local tz
    local_start = datetime.datetime.combine(
        target_date, datetime.time.min,
        tzinfo=datetime.timezone(datetime.timedelta(hours=tz_offset_hours))
    )
    local_end = local_start + datetime.timedelta(days=1)
    utc_start = local_start.astimezone(datetime.timezone.utc).isoformat()
    utc_end = local_end.astimezone(datetime.timezone.utc).isoformat()

    # Pull messages
    cur.execute(
        "SELECT m.message_id, m.chat_id, c.name, m.sender_name, m.msg_type, "
        "m.text, m.created_at, m.has_attachment, m.attachment_json "
        "FROM messages m LEFT JOIN chats c ON m.chat_id = c.chat_id "
        "WHERE m.created_at >= ? AND m.created_at < ? "
        "ORDER BY m.created_at",
        (utc_start, utc_end),
    )
    rows = cur.fetchall()
    conn.close()

    # Group by chat
    by_chat = {}
    for r in rows:
        by_chat.setdefault((r[1], r[2] or r[1]), []).append(r)

    # Build markdown
    out_dir = config.ARCHIVE_DIR / target_date.isoformat()
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / (target_date.isoformat() + ".md")

    lines = ["# Feishu Chat Archive — " + target_date.isoformat(), ""]
    lines.append("> Auto-generated by feishu-vault. Local-only, never uploaded.")
    lines.append("> Messages: " + str(len(rows)) + " | Chats: " + str(len(by_chat)))
    lines.append("")

    for (chat_id, chat_name), msgs in sorted(by_chat.items(), key=lambda x: x[0][1] or x[0][0]):
        lines.append("## " + (chat_name or chat_id))
        lines.append("")
        for m in msgs:
            msg_id, _, _, sender, msg_type, text, created_at, has_att, att_json = m
            # Format timestamp
            try:
                dt = datetime.datetime.fromisoformat(created_at.replace("Z", "+00:00"))
                local_dt = dt.astimezone(datetime.timezone(datetime.timedelta(hours=tz_offset_hours)))
                ts_str = local_dt.strftime("%H:%M:%S")
            except (ValueError, AttributeError):
                ts_str = created_at or "?"
            type_label = "" if msg_type == "text" else ("`[" + msg_type + "]` ")
            sender_str = sender or "<unknown>"
            text_clean = (text or "").replace("\n", "  \n")  # preserve linebreaks in md
            lines.append("- **" + ts_str + "** " + sender_str + ": " + type_label + text_clean)
            if has_att and att_json:
                try:
                    att = json.loads(att_json)
                    fname = att.get("file_name") or ("file_" + (att.get("file_key") or "")[:8])
                    lines.append("  - 📎 " + fname)
                except json.JSONDecodeError:
                    pass
        lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")

    config.write_audit("archive_complete",
                       date=target_date.isoformat(),
                       messages=len(rows),
                       chats=len(by_chat),
                       md_path=str(md_path))
    return {"md_path": str(md_path), "messages": len(rows), "chats": len(by_chat)}


def init_db_or_open():
    """Make sure DB exists; if not, lazy-init."""
    if not config.VAULT_DB.exists():
        from . import sync as _sync
        _sync.init_db()